export const paths = {
  main: '/',
  profile: '/profile',
  courses: '/courses',
  users: '/users',
  newuser: '/users/new',
  positions: '/position',
  login: '/login',
  registration: '/registration',
  firstenter: '/first-enter',
  recovery: '/recovery',
  newpass: 'new-password',
  otp: '/otp',
  admin: '/admin',
  employeeReg: '/first-login?',
};
