export const paths = {
  main: '/',
  profile: '/profile',
  courses: '/courses',
  newcourse: '/new-course',
  editcourse: '/courses/:id',
  users: '/users',
  edituser: '/users/:id',
  newuser: '/new-user',
  positions: '/position',
  newposition: '/new-position',
  editposition: '/position/:id',
  login: '/login',
  registration: '/registration',
  firstenter: '/first-enter?',
  recovery: '/recovery',
  newpass: 'new-password',
  otp: '/otp',
  admin: '/admin',
};
